services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASS:-pass}"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "${UI_PORT:-8081}:8081"
    links: 
      - db:db
    environment:
      - "PGWEB_DATABASE_URL=postgres://postgres:${DB_PASS:-pass}@db:${DB_PORT:-5432}/postgres?sslmode=disable"
    depends_on:
      - db
